/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mailbox.glb -T 
Files: mailbox.glb [672.6KB] > D:\Code\3D-Portfolio\public\models\mailbox-transformed.glb [84.86KB] (87%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Mailbox(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/mailbox-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Dummy001" position={[5.171, 141.468, -34.816]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
          <group name="Cylinder001" position={[6.625, -10.738, 9.669]} rotation={[1.716, 1.558, 2.996]} scale={0.866}>
            <mesh name="Cylinder001_07_-_Default_0" geometry={nodes['Cylinder001_07_-_Default_0'].geometry} material={materials['08_-_Default']} />
            <mesh name="Cylinder001_03_-_Default_0" geometry={nodes['Cylinder001_03_-_Default_0'].geometry} material={materials['09_-_Default']} />
            <mesh name="Cylinder001_02_-_Default_0" geometry={nodes['Cylinder001_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
            <mesh name="Cylinder001_01_-_Default_0" geometry={nodes['Cylinder001_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group name="Box002" position={[-2.728, -1.764, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh name="Box002_01_-_Default_0" geometry={nodes['Box002_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
        <mesh name="Tube001_01_-_Default_0" geometry={nodes['Tube001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-2.635, 165.935, -30.603]} rotation={[0.003, 0, 0]} scale={2.54} />
        <mesh name="Tube001_09_-_Default_0" geometry={nodes['Tube001_09_-_Default_0'].geometry} material={materials['09_-_Default']} position={[-2.635, 165.935, -30.603]} rotation={[0.003, 0, 0]} scale={2.54} />
        <mesh name="Tube001_08_-_Default_0" geometry={nodes['Tube001_08_-_Default_0'].geometry} material={materials['08_-_Default']} position={[-2.635, 165.935, -30.603]} rotation={[0.003, 0, 0]} scale={2.54} />
        <mesh name="Tube001_02_-_Default_0" geometry={nodes['Tube001_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-2.635, 165.935, -30.603]} rotation={[0.003, 0, 0]} scale={2.54} />
        <mesh name="Box006_15_-_Default_0" geometry={nodes['Box006_15_-_Default_0'].geometry} material={materials['15_-_Default']} position={[2.306, 145.253, 0.962]} rotation={[-1.475, 0.711, 2.996]} scale={[2.54, 2.49, 2.49]} />
        <mesh name="Box003_13_-_Default_0" geometry={nodes['Box003_13_-_Default_0'].geometry} material={materials['13_-_Default']} position={[-10.543, 143.27, 0.962]} rotation={[-Math.PI / 2, -0.716, 0]} scale={[2.54, 2.49, 2.49]} />
        <mesh name="Box004_14_-_Default_0" geometry={nodes['Box004_14_-_Default_0'].geometry} material={materials['14_-_Default']} position={[17.612, 143.27, 4.565]} rotation={[-1.571, -1.553, 0]} scale={[2.54, 2.49, 2.49]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mailbox-transformed.glb')
